"highlight Normal guifg=white guibg=black
set guifont=DejaVu\ Sans\ Mono\ 12
"set background=dark
"colorscheme solarized
colorscheme distinguished
set guioptions=gi
set columns=90
set guicursor=a:blinkon0
