"highlight Normal guifg=white guibg=black
set guifont=DejaVu\ Sans\ Mono\ 14
"set background=dark
"colorscheme solarized
colorscheme distinguished
set guioptions-=T guioptions-=m
set columns=90
set guicursor=a:blinkon0
